baseURL = "https://neu.gospelvoices.org/"
languageCode = "de-de"
theme = "gospelvoices-theme"
title = "Gospel Voices"
[markup.tableOfContents]
endLevel = 8
startLevel = 1


[params.fonts]
# sets the google font link in layouts/partials/google-fonts.html
google_fonts = 'https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600&family=Source+Sans+Pro:wght@400;700&display=swap'
heading = "Playfair Display"
base = "Source Sans Pro"

[params.logo]
mobile = "images/logo/logo.png"
mobile_height = "36px"
desktop = "images/logo/logo.png"
desktop_height = "36px"
alt = "Gospel Voices"

[params.colors]
primary = "#009ee0"
black = "#2f2f41"
white = "#ffffff"
white_offset = "#f6f7ff"
grey = "#5C5A5A"